name: Deploy API Example

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/example-api.yml'
      - 'example/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example/backend
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bearer-auth-react-context-api'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: './example/backend'
